[package]
name = "common"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["64"]
32 = []
64 = []

[dependencies]
anyhow = "1.0.95"
ndarray = "0.16.1"
paste = "1.0.15"
thiserror = "2.0.9"
